name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.sonar\cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\gradlew.bat sonarqube ^
            -Dsonar.projectKey=n1ck-b_Labs ^
            -Dsonar.organization=n1ck-b ^
            -Dsonar.host.url=https://sonarcloud.io
