name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        run: msbuild /t:Rebuild /p:Configuration=Release

      - name: Install SonarScanner and Build Wrapper
        uses: sonarsource/sonarcloud-github-action@v2

      - name: Run build-wrapper
        run: |
          build-wrapper-win-x86-64.exe --out-dir build_wrapper_output_directory msbuild /t:Rebuild /p:Configuration=Release

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sonar-scanner -Dsonar.cfamily.build-wrapper-output=build_wrapper_output_directory
